<?php
/**
 * Created by PhpStorm.
 * User: wodrow
 * Date: 11/18/16
 * Time: 1:57 PM
 */

namespace book\assets;

class AppAsset extends \yii\web\AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';

    public $css = [
    ];

    public $js = [
    ];

    public $depends;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->depends = [
            \yii\web\YiiAsset::className(),
            \common\assets\Bootstrap::className(),
        ];
    }
}