<?php
/**
 * Created by PhpStorm.
 * User: wodrow
 * Date: 12/24/16
 * Time: 3:59 PM
 */

namespace book\modules\shop\models;

use common\tools\Tools;

class Goods extends \book\models\Goods
{
    public function rules()
    {
        return [
            [['shop_id', 'brand_id', 'name', 'code', 'attribute_ids_str', 'status', 'location_area', 'location_info'], 'required'],
            [['shop_id', 'brand_id', 'created_at', 'updated_at', 'status', 'is_virtual', 'location_area'], 'integer'],
            [['name', 'title', 'code', 'cover', 'location_info'], 'string', 'max' => 255],
            ['attribute_ids_str', 'checkIds'],
        ];
    }

    public function checkIds($attribute, $params)
    {
        if (!is_array($this->attribute_ids_str))
            $this->addError($attribute, "格式错误");
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->attribute_ids_str = \GuzzleHttp\json_decode($this->attribute_ids_str);
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)){
            $this->attribute_ids_str = \GuzzleHttp\json_encode($this->attribute_ids_str);
            return true;
        }else{
            return false;
        }
    }
}