<?php

namespace book\modules\shop\controllers;

use book\modules\shop\models\GoodsSearch;
use book\modules\shop\models\Shop;
use book\modules\shop\models\ShopSearch;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

/**
 * Default controller for the `shop` module
 */
class DefaultController extends Controller
{
    private $_shop;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
//                        'actions' => ['*'],
                        'allow' => true,
                        'roles' => ['@',],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($shop_id = \Yii::$app->request->get('id')){
            $this->_shop = \book\models\Shop::findOne(['id'=>$shop_id, 'user_id'=>\Yii::$app->user->identity->id]);
            if (!$this->_shop){
                throw new Exception("不是你的店铺");
            }
        }
    }

    public function actionIndex()
    {
        $this->redirect(['my-shops']);
    }

    public function actionMyShops()
    {
        $searchModel = new ShopSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);

        return $this->render('my-shops', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        $goodsSearchModel = new GoodsSearch();
        $goodsDataProvider = $goodsSearchModel->search(\Yii::$app->request->queryParams);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'goodsSearchModel' => $goodsSearchModel,
            'goodsDataProvider' => $goodsDataProvider,
        ]);
    }

    public function actionCreateShop()
    {
        $model = new Shop();
        if ($model->load(\Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            var_dump($model->getErrors());
            return $this->render('create-shop', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(\Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = Shop::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}
