<?php

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/12/12 0012
 * Time: 19:37
 */
namespace book\modules\test\models;

class Shop extends \book\models\Shop
{
    public function beforeValidate()
    {
        if(parent::beforeValidate()){
            $this->user_id = \Yii::$app->user->getId();
            return true;
        }else{
            return false;
        }
    }
    
    public function attributeLabels()
    {
        $x = parent::attributeLabels(); // TODO: Change the autogenerated stub
        $x['name'] = "店铺名";
        return $x;
    }
}